### PR TITLE
Update README.md file for the new feature

### PR DESCRIPTION
**Pull request by JinleeJeong**
## Description

Update README.md file for the new feature

## Related Issues

x

## Tests

x

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by JinleeJeong** [comment]
After fixing the issue related to the datepicker test, I will deal with it!

**Comment by JeffGuKang** [comment]
@JinleeJeong Would you resolve conflicts? Datepicker snapshots were removed.

**Review by JeffGuKang — APPROVED** [review]
LGTM

**Comment by JinleeJeong** [comment]
> @JinleeJeong Would you resolve conflicts? Datepicker snapshots were removed.

@JeffGuKang  The test problem was solved. Thank you !! :)

**Pull request merged**
