### PR TITLE
[Feature][Branch] Type modification

### PR DESCRIPTION
**Pull request by smallbee3**
## Description
Modify the Mapped types used in **src/components/shared/Select/index.tsx** and
**src.components/shared/__tests__/Select.test.tsx**
I checked the related information from the below page.
(https://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types)

## Related Issues
#75

## Tests
NA

## Checklist
- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui-native/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Review by geoseong — CHANGES_REQUESTED** [review]
Thank you for taking this `type` to the next level! It helped a lot for me to learn **the mapped type**.

but can you change this PR's name from `[Feature][Branch] Select -> "Root" section` to `[Feature][Branch][Select] type modification` ? thanks in advance.

**Comment by smallbee3** [comment]
Yep!
I changed the title of the pull request.

Is there anything else I need to do to make this pull request merged ?
Because I will recreate my pull request(#80 is closed) after this pull request is merged.

@dlgmltjr0925 @geoseong

**Review by geoseong — APPROVED** [review]
there's nothing else to fix, thanks~!

**Comment by dlgmltjr0925** [comment]
Good job!!

**Pull request merged**
