### PR TITLE
Add SearchInput

### PR DESCRIPTION
**Pull request by godon019**
## Description

image

--- 
 - use debounce delay for better ux when filtering the result

 - custom placeholder

 
 - reset button

Added Search Input component
Added story for play with it
- [x] Add doc

## Related Issues

none

## Tests

I added the following tests:

- [x] doesn't show reset button when no input
- [x] show reset button when input exists

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui-native/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Review by hyochan — COMMENTED** [review]
Is this still in progress?

**Comment by godon019** [comment]
> Is this still in progress?

Yes I will add doc file about it soon!

**Comment by godon019** [comment]
> Is this still in progress?

This is done now!

**Review by hyochan — APPROVED** [review]
Looks great! Thanks for your hard work agian 💯

**Pull request merged**
