### PR TITLE
[Boilerplate][Branch] Slider sample screen => feat/slider branch

### PR DESCRIPTION
**Pull request by daheeahn**
## Description

Init Feat/Slider
- I added Slider folder and test file.

## Related Issues

related #41 

## Tests

I used dooboo-cli.
`dooboo shared Slider` so test file was created automatically!

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui-native/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by daheeahn** [comment]
We should set STORYBOOK_START = false ! then you can see SliderSample.tsx

**Comment by hyochan** [comment]
@daheeahn Thanks for the quick movement. Since we have the storybook installed(previously, we didn't have this), you can try to set this up in `stories` as we did in other components (example [this](https://github.com/dooboolab/dooboo-ui-native/blob/master/storybook/stories/Button.stories.tsx)). Making more `sample` screens will make massive useless screens when more components grow in our module.

**Comment by hyochan** [comment]
@YongPilMoon Your teammate is working hard!

**Comment by Sandwichj** [comment]
Thank you for this PR!

**Comment by Sandwichj** [comment]
Checked for your changes from the boilerplate created by `dooboo-cli`.
Nice start! Thanks again.
I'll merge for this. :)

**Review by Sandwichj — APPROVED** [review]

**Pull request merged**
