### PR TITLE
Change Container Style in stories/Button

### PR DESCRIPTION
**Pull request by sk97kang**
## Description

There was excessive margin and padding.
So part of the last button was not visible.

### As-Is

image

### To-Be

image

## Related Issues

X

## Tests

X

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Review by hyochan — CHANGES_REQUESTED** [review]
Thanks for the `PR`. Could you kindly post additional picture (in description) that describes your changes?

**Comment by sk97kang** [comment]
> Thanks for the `PR`. Could you kindly post additional picture (in description) that describes your changes?

Your request has been confirmed and added.

**Comment by JongtaekChoi** [comment]
Hmm... I don't think that it solves the problem. Because the problem is related to screen height. So I prefer to use ScrollView than modify the layout.

**Comment by JeffGuKang** [comment]
@sk97kang How about to use `ScrollView` to resolve container's height issue like @JongtaekChoi said? or use flex for dynamical layout as `space-around`.

**Comment by sk97kang** [comment]
> @sk97kang How about to use `ScrollView` to resolve container's height issue like @JongtaekChoi said? or use flex for dynamical layout as `space-around`.

I added the `scrollview` to include the existing container.

**Review by JeffGuKang — APPROVED** [review]

**Comment by JeffGuKang** [comment]
> Thanks for the `PR`. Could you kindly post additional picture (in description) that describes your changes?
@hyochan The request was solved. 👍

**Review by hyochan — APPROVED** [review]
Nice~

**Pull request merged**
