### PR TITLE
Initial migration for supporting universal layout (ios, web, android)

### LINKED ISSUE #197: Implementation on web env
Since #196 has been merged, we can drive forward to web implementation.

After we've tested implementing UI components in web, we can think of publishing our new packages and deprecate all previous `@dooboo-ui/native-*` packages.

## TODO
- [x] React (web) storybook implementation and publishing to github pages.
   - Reference
      * https://github.com/storybookjs/storybook/issues/2963
      * https://github.com/necolas/react-native-web/blob/0.5.1/website/package.json
- [x] Web implementation for all components we've worked on.

### PR DESCRIPTION
**Pull request by hyochan**
## Description

We are willing to support universal `react-native` platforms in `dooboo-ui`. Here is an initial work that works in all layouts (web, ios, android) in a storybook with typescript.

**[Storybook for web]**
8w4dVL0NlP

**[Storybook for mobile]**
LJlLPahAKA

**[Note on publishing `dooboo-ui` to npm]**

```
yarn build
cd lib && yarn publish
```

**[Note on building `@dooboo-ui plugins` to npm]**

```
yarn build-packages
npx lerna publish
```

## Related Issues

#194 Closes #197

## Tests

Fix all broken tests and made `main/__tests__` and `pacakge/__tests__` to work.

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by hyochan** [comment]
@JeffGuKang I think I made it now! It works on `web`, `ios` and `android`!

**Comment by hyochan** [comment]
@JeffGuKang Since `.storybook` file can't be imported in `react-native` mobile, I've created a `postinstall` script to cp `storybook` from `.storybook` and ignore `storybook` totally which is a waste to be recorded in the git history.

**Comment by JeffGuKang** [comment]
`main/Rating` has images and there is no options to copy assets when we use `tsc`. How about using `postbuild` to copy assets? 

```
"postbuild": "cp -r main/Rating/images lib/Rating/images",
```
or if we manage assets with one folder as 'main/assets'.
```
"postbuild": "cp -r main/assets lib/assets",
```

**Comment by hyochan** [comment]
> `main/Rating` has images and there is no options to copy assets when we use `tsc`. How about using `postbuild` to copy assets?
> 
> ```
> "postbuild": "cp -r main/Rating/images lib/Rating/images",
> ```
> 
> or if we manage assets with one folder as 'main/assets'.
> 
> ```
> "postbuild": "cp -r main/assets lib/assets",
> ```

Thanks for the gotcha. I've updated as you've requested. Also, I've managed to change the dir name to `main/__assets__`. Since it is more clearer to watch at first glance where the assets should belong to (Yeah. It is right at the top).

**Review by JeffGuKang — APPROVED** [review]

**Review by JeffGuKang — APPROVED** [review]
This is a huge update! LGTM.

**Pull request merged**
