### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by samslow**
Signed-off-by: samslow <shsvkdldj@likelion.org>

## Description

Remove unnecessary steps

* pod install step is not necessary because not exist ios directory now

* I don't know if it's an intentional commit, `"git:log": "git log --decorate --oneline --all --graph"` was removed on [supporting universal layout commit](https://github.com/dooboolab/dooboo-ui/commit/84315d2ed8e096f48119620da4d7288711a8ca2b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2). but If it should remain, we should add it on `scripts`in `package.json`.

## Related Issues

N/A

## Tests

this PR don't need any test

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by hyochan** [comment]
Hm.. can someone tell why the `Greetings` is failing?

**Comment by samslow** [comment]
`I understood that this message was of course a message to the first PR person.`
@hyochan I understood that this message was of course a message to the first PR person.
I'll find out more.

**Review by hyochan — APPROVED** [review]
LGTM!

**Comment by hyochan** [comment]
> `I understood that this message was of course a message to the first PR person.`
> @hyochan I understood that this message was of course a message to the first PR person.
> I'll find out more.

Actually, we can ignore this for this case. I don't think this is important. However, we can find out more next time! Thanks for the contribution 👍

**Pull request merged**
