### PR TITLE
New component PinchZoom

### PR DESCRIPTION
**Pull request by JongtaekChoi**
## Description

I propose to add this PinchZoom to dooboo-ui.
Just wrapping the child component makes it zoomable like below.

Aug-25-2020 00-01-58

Also, by using PinchZoom you can make screen like below.
Aug-31-2020 15-29-39

Readme of this is [here](https://github.com/JongtaekChoi/dooboo-ui/tree/feature/pinch-zoom/main/PinchZoom)

## Related Issues

#316 

## Tests

I added the following tests:

- Simple snapshot tests of the list of Images wrapped by PinchZoom.
- Zoom-in action and release action of each pinch-zoomed Image.

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Review by hyochan — CHANGES_REQUESTED** [review]
@JongtaekChoi Could you change the latest image in description?

**Comment by JongtaekChoi** [comment]
@hyochan Sure!

**Comment by hyochan** [comment]
@JongtaekChoi Why closed?

**Comment by JongtaekChoi** [comment]
I thought that I merged this pr...

**Pull request merged**
