### PR TITLE
[Feature][Branch] Select -> "Root" section

### PR DESCRIPTION
**Pull request by geoseong**
### 🙋🏻‍♂️ please do not merge this until making TODO done

root section in feat/select
스크린샷 2019-12-10 오후 4 54 47

- add **theme** prop: `none`, `box`, `underline`
- add **rootViewStyle** prop: custom `ViewStyle` stylesheet to root part of selectbox's view
- add **rootTextStyle** prop: custom `TextStyle` stylesheet to root part of selectbox's text

## Related Issues

#60 

## Tests

- check theme and rootTextStyle and placeholder with case "notheme"
- check theme and rootTextStyle and placeholder with case "inputTheme"
- check theme and rootViewStyle and placeholder with case "themeAndRootView"
- check theme & rootViewStyle & rootTextTheme and placeholder with case "disabled"

## TODO

- [x] make styling **box-shadow** looking good
- [x] typechecking using `tsc`
- [x] making test code related this

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui-native/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Review by dlgmltjr0925 — APPROVED** [review]
It seems we need a style for disable.

**Comment by geoseong** [comment]
> It seems we need a style for disable.

@dlgmltjr0925 I add style for disable!

**Comment by hyochan** [comment]
It can be off-topic but looks like @geoseong has merged the branch instead of rebasing which causes bringing all the prev commits to history.

One of good rebased sample is [here](https://github.com/dooboolab/dooboo-ui-native/pull/81/commits).
We should only see commits from the committer.

**Comment by geoseong** [comment]
@hyochan I got it. I modified commit histories

**Comment by dlgmltjr0925** [comment]
@geoseong Thank you for your efforts in #62 and #75!!.
While testing with your code, I found something wrong in "Props" interface that I didn't see in the review. So I ask you to fix it.

export interface Props {
   ...
  **placeholder?: boolean;   <-- edit here boolean to string** 
  ...
}

**Comment by geoseong** [comment]
@dlgmltjr0925 sorry I missed it. I will modify this type and issue PR shortly.

**Pull request merged**
