### PR TITLE
[Feature][Chart][BarChart] Added main source of BarChart

### PR DESCRIPTION
**Pull request by filoscoder**
## Description

Added main source of packages/BarChart, is working properly on Expo web **ONLY**!

Review BarChart code please, still WIP.

## Related Issues
https://github.com/dooboolab/prime-expo/pull/26

I'm facing an issue while running iOS simulator & Android simulator.
- iOS Error:

> Invariant Violation: "main" has not been registered. This can happen if: * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.

- Android Error:
>Invariant Violation tried to register two views with the same name RNSVGSvgView

## Tests

Planning to write test code after debugging mobile simulator errors.

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [ ] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [ ] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by hyochan** [comment]
Is this ready? Then please rebase this and remove word `WIP`.

**Comment by filoscoder** [comment]
> Is this ready? Then please rebase this and remove word `WIP`.

 Not yet, I'll have to resolve the conflicts and write the test code before.
When it is ready I'll let you know!

Thanks for keep tracking the PR :)

**Comment by filoscoder** [comment]
The PR is ready to review! @hyochan

**Review by hyochan — CHANGES_REQUESTED** [review]
image

Please re-request review after updating storybook!

**Pull request closed without merging**
