### PR TITLE
[WIP][Feature][Branch] Slider track

### PR DESCRIPTION
**Pull request by daheeahn**
## Description

I don't have the styled component yet and made it my style so I don't want this PR to merge.
Just see my code!
1) I'm wondering about moving big end point. because I used just 'useState'.
2) I'm wondering about return 10 TouchableOpacity not using my way (line 32)
I only made slider with TouchableOpacity, View. 
Thank you for your understanding as it is very incomplete 😅

## Related Issues
#41 #47

### CODE REVIEW

**Comment by daheeahn** [comment]
image

**Comment by Sandwichj** [comment]
A good try to implement the moving gesture. 👍 
May be hard to implement a gesture feature by hand.

I don't know much about RN, but searching `react-native` API reference is an easy thing to know what we need.

`react-native` provides a gesture interface on `View` component. (single-touch)
- https://facebook.github.io/react-native/docs/gesture-responder-system

`PanResponder` is a wrapper feature of the gesture system for multi-touch.
- https://facebook.github.io/react-native/docs/panresponder

@YongPilMoon added a `sample code` of `PanResponder` to design [Slider] interface.
It shows how to start with `PanResponder`. #49 

Implementing [Track] component is yours now. You can try anything you want to implement the feature. `View`, `PanResponder` or others.

**Comment by Sandwichj** [comment]
The `big end point` that you mentioned, is called `Thumb` or `Marker` in general. :)
Thumb

I guess from your code, you mean that the way to move `Thumb` is by touching the mark on the [Rail].
[Slider] of hackatalk UI design has no marks by default...  :'-(
Some users may want to move `Thumb` by pressing `Thumb`.
Slider

**Comment by Sandwichj** [comment]
How about separating [Track] component in a separated component/test files?

[Slider] file should be for combining the sub-components [Rail], [Track], [Thumb] and [Label].

The purpose is for implementing them by concentrating on each component.
And for less code conflicts as well by implementing in separated files.

**Comment by Sandwichj** [comment]
It's a nice try! Hope you come back to contribute again. 👍

**Pull request closed without merging**
