### PR TITLE
Refactor [Button]

### PR DESCRIPTION
**Pull request by cloudpracj**
## Description
Issued at dooboolab/hackatalk-mobile#34.

- Refactored.
  - Arranged element structure.
  - Extracted colors as constants.
- Changed props.
  - `leftComponent` -> `iconLeft` / `iconRight`
  - Deprecated `disabledStyle`. Instead, use `theme`.
  - Deprecated `textStyle`. Instead, use `theme`.
- Added props.
  - `theme` to custom primary styles.
  - `dark` to use dark theme.
  - `inverted` to invert style.
  - Possible to use block component. (`children`)
- Improved design.
  - The basic design has not changed.
  - Added inverted design.
  - Added dark design.
  - Avaliable to use the both `styled-components` and `StyleSheet`.
- Updated the specified package version to 0.3.0.
- It is not compatible with the previous version.

## Related Issues

It will be used for dooboolab/hackatalk-mobile#34.

## Tests

Replaced with [Button] test of dooboolab/hackatalk-mobile#34.
Improving the test would be the next step.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui-native/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Review by hyochan — COMMENTED** [review]
Awesome. Could you show me later how you've applied this to `hackatalk-mobile` and it works correctly?

**Comment by cloudpracj** [comment]
Sure! :)
I'll create a PR in `hackatalk-mobile`, to resolve dooboolab/hackatalk-mobile#34 as well later.

These are custom buttons by [Button]. This shows how to use it.

- with `StyleSheet`
- with icons for a sample.



- with `styled-components`




p.s.
`dark` and `inverted` props show default styles defined in [Button].
 `theme` prop overrides the default styles.
For example, if `backgroundColor` is defined in `theme`, it shows always the defined `backgroundColor`, not default. Developers should pass own inverted, dark or other styles if they want. :)

**Comment by Sandwichj** [comment]
Sure! :)
I'll create a PR in `hackatalk-mobile`, to resolve dooboolab/hackatalk-mobile#34 as well later.

Custom buttons. They show how to use it.

- with `StyleSheet`
- with icons for a sample.



- with `styled-components`




p.s.
`dark` and `inverted` props show default styles defined in [Button].
 `theme` prop overrides the default styles.
For example, if `backgroundColor` is defined in `theme`, it shows always the defined `backgroundColor`, not default. Developers should pass own inverted, dark or other styles if they want. :)

**Comment by Sandwichj** [comment]
`backgroundColor` ane `borderColor` should be renamed to `DefaultTheme` type to match the format of `react-native`'s, or rename `theme` prop.
What do you think about it?

**Comment by Sandwichj** [comment]
I modified it to export `ThemeType` of [Button] to fit a custom `DefaultTheme`.
A better solution for using `styled-components`.

- with `StyleSheet`
```jsx
import Button from '@dooboo-ui/native';

<Button
  testID="sampleButton"
  style={{
    width: 136,
    height: 60,
    borderWidth: 1,
  }}
  theme={{
    ...theme,  // If the project uses a custom 'DefaultTheme' like 'dooboolab/hackatalk-mobile'
    backgroundColor: 'black',
    borderColor: 'red',
    fontColor: theme.btnPrimaryLightFont,
  }}
  onClick={(): void => {}}
>
    Sign up
</Button>
```

- with `styled-components`
- It should override `ThemeType` to use the theme type of [Button].
- Does anyone have a better solution to specify `StyledComponent` type to override `ThemeType`?
```jsx
import Button, { ThemeType } from '@dooboo-ui/native';

const SampleButton: StyledComponent< // any better solution?
  typeof Button,
  ThemeType,  // To override a custom 'DefaultTheme'. It is auto-typed with 'DefaultTheme' by default.
  {},
  never
> = styled(Button)`
  width: 136px;
  height: 60px;
  border-width: 1px;
`;
```

```jsx
<SampleButton
  testID="sampleButton"
  theme={{   // ThemeType
    ...theme,  // If the project uses a custom 'DefaultTheme' like 'dooboolab/hackatalk-mobile'
    backgroundColor: 'black',
    borderColor: 'red',
    fontColor: theme.btnPrimaryLightFont,
  }}
  onClick={(): void => {}}
>
    Sign up
</SampleButton>
```

**Comment by hyochan** [comment]
@marsinearth @godon019 Please take a look at this wonderful `PR`. We need your thoughts.

**Comment by godon019** [comment]
This seems awesome, I will read it thoroughly and think about the solutions for custom theme overriding

**Comment by godon019** [comment]
> backgroundColor

Could you elaborate it more please?

**Comment by godon019** [comment]
> `backgroundColor` ane `borderColor` should be renamed to `DefaultTheme` type to match the format of `react-native`'s, or rename `theme` prop.
> What do you think about it?

Could you elaborate it more please?

**Comment by Sandwichj** [comment]
@godon019
Sorry for confusing you. I didn't know that dooboolab/hackatalk-mobile uses custom `DefaultTheme` at the time. Please ignore the replay.

**Comment by godon019** [comment]
That is fine.
So if the hackatalk has its own DefaultTheme, then this will use hackatalk’s DefaultTheme instead of dooboo-ui-native’s right? And you wanna have a better solution then explicitely override it like you mentioned above

**Comment by Sandwichj** [comment]
@godon019 
Yeah, a component will use custom `DefaultTheme` when to wrap by `styled()` if dooboolab/hackatalk-mobile has own `DefaultTheme`.

That's why I defined the type for the component as following.

```jsx
import Button, { ThemeType } from '@dooboo-ui/native';

const SampleButton: StyledComponent< // any better solution?
  typeof Button,
  ThemeType,  // To override a custom 'DefaultTheme'. It is auto-typed with 'DefaultTheme' by default.
  {},
  never
> = styled(Button)`
  width: 136px;
  height: 60px;
  border-width: 1px;
`;
```

By default, the type of `SampleButton` is:
```jsx
const SampleButton: StyledComponent<
  typeof Button,
  DefaultTheme,
  {},
  never
>
```

But it should be `ThemeType` of [Button]:
```jsx
const SampleButton: StyledComponent<
  typeof Button,
  ThemeType,
  {},
  never
>
```

The way to specify another theme type for `StyledComponent` looks not easy to maintain. :(
Any idea to specify `ThemeType` for the component?

**Review by godon019 — APPROVED** [review]
Awesome ! Thanks for your contribution!

**Comment by godon019** [comment]
We will think about enhanced solution in the future!

**Comment by Sandwichj** [comment]
Updated README.md.
Now available to customize text styles bypassing `children` prop as `ReactElement` for using `styled-components`.

**Review by godon019 — APPROVED** [review]
Love your contribution! 🎉

**Review by marsinearth — COMMENTED** [review]
I briefly looked at the code and think that injecting whole theme is not a good idea, since some themes can have different theme prop names rather than `backgroundColor` or `borderColor` at [this part](https://github.com/dooboolab/dooboo-ui-native/pull/28/files#diff-bd04c71824767f3cc922774076a3aca9R110). I suggest to get the external props directly, such as 
```typescript
const StyledButton = styled.View<ButtonType & TextType>`
  background-color: ${({ theme, backgroundColor }): string => backgroundColor || theme.backgroundColor};
  border-color: ${({ theme, borderColor }): string => borderColor || theme.borderColor};
`;
```
You can get all the external styles in some props such as
```typescript
// in applied script
import Button from '@dooboo-ui/native';

<Button
  containerStyle={{
    borderColor: 'someColor',
    backgroundColor: 'anotherPrettyColor',
  }}
  innerStyle={{
    fontColor: 'awesomeColor',
    fontSize: 'bigAndGorgeous',
    fontWeight: 'boldest',
  }}
/>
```
or something like that.

btw, this is a lot of work and effort. Thank you so much!

**Comment by Sandwichj** [comment]
@marsinearth 
Thank you for your review. The things you caught are important issues for building component architecture.
I found a solution to apply theme and styles with some criterias, thanks to you lead me.

For the first one,
I separated `style` and `theme`.

- `style`
  - `style` is passed by outer component.

- `theme`  
  - `theme` is used only for [Button].
  - `theme` is typed with [ButtonThemeType] or [TextThemeType].
  - No other styles is defined for `theme`. And `theme` is not a prop anymore.

- `style` and `theme` are combined and put into each inner component of [Button].

```jsx
interface ThemeType extends DefaultTheme {
  backgroundColor: string;
  borderColor: string;
  fontColor: string;
}
```
```jsx
const buttonThemeToApply: ButtonThemeType = {
  backgroundColor: buttonStyleToApply.backgroundColor || defaultTheme.backgroundColor,
  borderColor: buttonStyleToApply.borderColor || defaultTheme.borderColor,
};
const textThemeToApply: TextThemeType = {
  fontColor: textStyleToApply.color || defaultTheme.fontColor,
};
```

About the second one,
I restored `textStyle` prop for styling `text` as you mentioned.
But I have a different perspective on it. The reasons are as follows.
- `style` prop is a common interface in `react-native`.
- A complete component is with `style`.
- A component has many custom inner components, leads to code generalization. (Generalized code is hard to maintain, and it breaks code consistency in many cases.)

I named `style` and `textStyle` because `Composite` pattern is preferred for consistency of a component or a project in many cases.


- with `StyleSheet`
```jsx
<SampleButton
  testID="sampleButton"
  style={{
    backgroundColor: 'red',
    borderColor: 'blue',
  }}
  textStyle={{
    color: 'white',
  }}
  onClick={(): void => {}}
>
  Sample button
</SampleButton>
```
```jsx
<SampleButton
  testID="sampleButton"
  style={{
    backgroundColor: 'red',
    borderColor: 'blue',
  }}
  onClick={(): void => {}}
>
  <SampleText>Sample button</SampleText>
</SampleButton>
```

- with `styled-components`
```jsx
const SampleButton = styled(Button)`
  width: 136px;
  height: 60px;
  background-color: black;
  border-color: red;
  border-width: 1px;
`;
const SampleText = styled.Text`
  color: white;
`;
<SampleButton
  testID="sampleButton"
  textStyle={{
    color: 'white',
  }}
  onClick={(): void => {}}
>
  Sample button
</SampleButton>
```
```jsx
const SampleButton = styled(Button)`
  width: 136px;
  height: 60px;
  background-color: black;
  border-color: red;
  border-width: 1px;
`;
const SampleText = styled.Text`
  color: white;
`;
<SampleButton
  testID="sampleButton"
  onClick={(): void => {}}
>
  <SampleText>Sample button</SampleText>
</SampleButton>
```

**Review by marsinearth — APPROVED** [review]
awesome!

**Review by hyochan — APPROVED** [review]
:+1:

**Pull request merged**
