### PR TITLE
[Feature] Rating component

### LINKED ISSUE #53: [Feature Request] Rating
**Is your feature request related to a problem? Please describe.**

New Rating component related to #37.

**Describe the solution you'd like**

Ref: https://material-ui.com/components/rating
Do not use external library such as `react-native-vector-icon`.

**Describe alternatives you've considered**
-

**Additional context**
-

### PR DESCRIPTION
**Pull request by JeffGuKang**
## Description

Feature: Rating component. 

## Related Issues

Resolves #53 

## Tests

I added the following tests:

Test CLI: `yarn jest Rating`
Test file path: `src/shared/shared/__tests__/Rating.test.tsx`
Story: `storybook/stories/Rating.stories.tsx`

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui-native/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by JeffGuKang** [comment]
Need to reflect #193 to pass CI test.

**Comment by JeffGuKang** [comment]
CI test failed with only [LoadingIndicator]. It looks OK with [Rating].

**Review by hyochan — CHANGES_REQUESTED** [review]
Test is still failing. No matter what, it would be great to resolve all the tests failing in your `PR`.

**Review by hyochan — APPROVED** [review]
Finally! We have a beautiful rating 👍

**Pull request merged**
