### PR TITLE
docs : fix typo Select README.md

### PR DESCRIPTION
**Pull request by JinleeJeong**
## Description

Fixed Typo Select component README.md

## Related Issues

X

## Tests

X

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes ([x]). This will ensure a smooth and quick review process.

### CODE REVIEW

**Review by samslow — APPROVED** [review]
You have sharp eyes.

**Comment by hyochan** [comment]
@JeffGuKang But we need to fix what the `CalendarCarousel` needs snapshot updates every time.

**Comment by JeffGuKang** [comment]
Could you rebase and force push this PR? Wrong test code was fixed.

**Comment by JinleeJeong** [comment]
@JeffGuKang After rebasing the code, the processing is complete! :) Is it correct?

**Pull request merged**
