### PR TITLE
Implement [SimpleButton].

### PR DESCRIPTION
**Pull request by Sandwichj**
Issued at https://github.com/dooboolab/hackatalk-mobile/issues/34.

**This PR is not for merging to master.**
I need to know some stories about [Button] of this repo and [SimpleButton] that I would migrate.

## Description
Implemented a component called [SimpleButton], the name is temporary to avoid the same name to [Button] which already exists.
- [SimpleButton] is almost ready to migrate from https://github.com/dooboolab/hackatalk-mobile/blob/master/src/components/shared/Button.tsx for reusability.
- Before finishing the implementation of [SimpleButton], I need to know about [Button] of this repo, to merge and arrange them.
- After that all issues related are resolved for the buttons, I'll merge them as a [Button] and ask the real PR.

## Related Issues

I have questions as following,
- I need to know the side-effects by changing the props(interface) if possible to re-design and refactor [Button].
  - I think that some of props of [Button](https://github.com/dooboolab/dooboo-ui-native/tree/master/src/components/shared/Button) should be re-designed to have clear meanings.
    - `onClick` -> `onPress`
    - `leftComponent` -> `icon`
    - deprecate `style`to refactor to `styled-components`
    - etc.
- [SimpleButton] has dark theme in the code as was in `hacktalk-mobile`, not styled yet.
  - Should `@dooboo-ui/native` have dark theme? if so, we need to design a structure to apply dark theme to all components as well.

## Tests

- No additional tests.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui-native/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Review by hyochan — CHANGES_REQUESTED** [review]
`lint` is throwing error in `ci`.

**Comment by Sandwichj** [comment]
@hyochan
This PR is not for merging to master yet.
Could you please check the `Related issues` section?
It's about merging the buttons without any critical side-effects.

**Comment by hyochan** [comment]
@Sandwichj Thank you for your insight. I'll try to go over issues you've provided in this `PR`.

>   * I think that some of props of [Button](https://github.com/dooboolab/dooboo-ui-native/tree/master/src/components/shared/Button) should be re-designed to have clear meanings.
>     
>     * `onClick` -> `onPress`

This is fine, but I've have refered to `material-ui` that they customized the props `onPress` to `onClick` which is more widely used in `android` world.

>     * `leftComponent` -> `icon`

This is fine either but I just want to point out that there could be a case where the icon could stay at the right. Therefore, `iconRight` and `iconLeft` could be candidates.

>     * deprecate `style`to refactor to `styled-components`
I don't quite agree with this because all of the style props can't be managed as separate props because there are too many. User should have the chance to change the style with `style` props without the `styled-component`.

> * [SimpleButton] has dark theme in the code as was in `hacktalk-mobile`, not styled yet.
> * Should `@dooboo-ui/native` have dark theme? if so, we need to design a structure to apply dark theme to all components as well.

Currently, we are passing different colors for `dark theme` to the `shared` components. It is recommended to guide users how they can organize the `dooboo-ui/native` components with separate `theming` variables like how many other libraries do (ex. `withTheme`). We currently need good solution for this.

Hope my answers resolve your curiosity. 🙏

**Comment by Sandwichj** [comment]
@hyochan 
Thanks a lot for your answers.
I make sense and agree all with your opinions of the answers.
I'll code as following for this issue.
- `onPress` -> `onClick` for more widely used convention.
- `icon` -> `iconLeft`, `iconRight`. Nice idea!
- Keep `style` as a prop for using in variable conditions. Also, I'll set possible to use `styled-components` as well.
- I'll think a structure to use dark theme for customs as well as a default dark theme. It can be better more and more.

I'll close this PR and re-request with better codes later. :)

**Pull request closed without merging**
